// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flowFlowKey struct {
	_             structs.HostLayout
	SrcIp         uint32
	DstIp         uint32
	SrcPort       uint16
	DstPort       uint16
	Protocol      uint8
	FlowDirection uint8
	Pad           [2]uint8
}

type flowFlowStats struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Pad        uint32
	Generation uint64
	Packets    uint64
	Bytes      uint64
	FirstSeen  uint64
	LastSeen   uint64
	TcpFlags   uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	flowMapDropCounters        = "drop_counters"
	flowMapFlowGeneration      = "flow_generation"
	flowMapFlows               = "flows"
	flowProgFlowCaptureEgress  = "flow_capture_egress"
	flowProgFlowCaptureIngress = "flow_capture_ingress"
	flowVarL2HdrLen            = "l2_hdr_len"
)

// loadFlow returns the embedded CollectionSpec for flow.
func loadFlow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flow: %w", err)
	}

	return spec, err
}

// loadFlowObjects loads flow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowObjects
//	*flowPrograms
//	*flowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowSpecs struct {
	flowProgramSpecs
	flowMapSpecs
	flowVariableSpecs
}

// flowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowProgramSpecs struct {
	FlowCaptureEgress  *ebpf.ProgramSpec `ebpf:"flow_capture_egress"`
	FlowCaptureIngress *ebpf.ProgramSpec `ebpf:"flow_capture_ingress"`
}

// flowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowMapSpecs struct {
	DropCounters   *ebpf.MapSpec `ebpf:"drop_counters"`
	FlowGeneration *ebpf.MapSpec `ebpf:"flow_generation"`
	Flows          *ebpf.MapSpec `ebpf:"flows"`
}

// flowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowVariableSpecs struct {
	L2HdrLen *ebpf.VariableSpec `ebpf:"l2_hdr_len"`
}

// flowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowObjects struct {
	flowPrograms
	flowMaps
	flowVariables
}

func (o *flowObjects) Close() error {
	return _FlowClose(
		&o.flowPrograms,
		&o.flowMaps,
	)
}

// flowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowMaps struct {
	DropCounters   *ebpf.Map `ebpf:"drop_counters"`
	FlowGeneration *ebpf.Map `ebpf:"flow_generation"`
	Flows          *ebpf.Map `ebpf:"flows"`
}

func (m *flowMaps) Close() error {
	return _FlowClose(
		m.DropCounters,
		m.FlowGeneration,
		m.Flows,
	)
}

// flowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowVariables struct {
	L2HdrLen *ebpf.Variable `ebpf:"l2_hdr_len"`
}

// flowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowPrograms struct {
	FlowCaptureEgress  *ebpf.Program `ebpf:"flow_capture_egress"`
	FlowCaptureIngress *ebpf.Program `ebpf:"flow_capture_ingress"`
}

func (p *flowPrograms) Close() error {
	return _FlowClose(
		p.FlowCaptureEgress,
		p.FlowCaptureIngress,
	)
}

func _FlowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flow_bpfeb.o
var _FlowBytes []byte
